export const PRODUITS_FORGE = [
  {
    nom: "TAAMA",
    slug: "taama",
    categorie: "Agriculture",
    description: "Traçabilité et gestion des coopératives agricoles",
    statut: "Actif" as const,
    couleur: "#22C55E",
    icon: "🌾",
    metriques: { utilisateurs: 1240, transactions: 8900, ca: 45000000 },
    url: "https://taama.vercel.app",
  },
  {
    nom: "MIFA Life",
    slug: "mifa-life",
    categorie: "E-commerce",
    description: "Marketplace mode africaine et artisanat premium",
    statut: "Actif" as const,
    couleur: "#F59E0B",
    icon: "👗",
    metriques: { utilisateurs: 3400, transactions: 12000, ca: 78000000 },
    url: "https://mifa-life.vercel.app",
  },
  {
    nom: "FORJA",
    slug: "forja",
    categorie: "Industrie",
    description: "Gestion des exportations et filières industrielles",
    statut: "Actif" as const,
    couleur: "#3B82F6",
    icon: "⚙️",
    metriques: { utilisateurs: 560, transactions: 2100, ca: 120000000 },
    url: "https://forja.vercel.app",
  },
  {
    nom: "CompTrack",
    slug: "comptrack",
    categorie: "Finance",
    description: "Logiciel comptabilité pour PME africaines",
    statut: "Actif" as const,
    couleur: "#8B5CF6",
    icon: "📊",
    metriques: { utilisateurs: 890, transactions: 45000, ca: 35000000 },
    url: "https://comptrack.vercel.app",
  },
  {
    nom: "AgroTrack BF",
    slug: "agrotrack-bf",
    categorie: "Agriculture",
    description: "Gestion collectes et membres coopératives Burkina",
    statut: "Actif" as const,
    couleur: "#10B981",
    icon: "🌿",
    metriques: { utilisateurs: 2100, transactions: 15600, ca: 62000000 },
    url: "https://agrotrack-bf.vercel.app",
  },
  {
    nom: "MillTrack",
    slug: "milltrack",
    categorie: "Industrie",
    description: "Gestion production minoteries et huileries",
    statut: "Actif" as const,
    couleur: "#F97316",
    icon: "🏭",
    metriques: { utilisateurs: 340, transactions: 4500, ca: 89000000 },
    url: "https://milltrack.vercel.app",
  },
  {
    nom: "LivestockOS",
    slug: "livestockos",
    categorie: "Élevage",
    description: "Gestion troupeaux, santé animale et marchés bétail",
    statut: "Actif" as const,
    couleur: "#EF4444",
    icon: "🐄",
    metriques: { utilisateurs: 780, transactions: 6700, ca: 41000000 },
    url: "https://livestockos.vercel.app",
  },
  {
    nom: "ValueChain Connect",
    slug: "valuechain-connect",
    categorie: "Commerce",
    description: "Marketplace B2B producteurs et transformateurs",
    statut: "Actif" as const,
    couleur: "#06B6D4",
    icon: "🔗",
    metriques: { utilisateurs: 1560, transactions: 9800, ca: 95000000 },
    url: "https://valuechain.vercel.app",
  },
  {
    nom: "FORGE Afrika HQ",
    slug: "hq",
    categorie: "Plateforme",
    description: "Centre de commande de l'écosystème FORGE",
    statut: "En cours" as const,
    couleur: "#D4AF37",
    icon: "🏛️",
    metriques: { utilisateurs: 0, transactions: 0, ca: 0 },
    url: "/",
  },
] as const;

export const CATEGORIES = [
  "Tous",
  "Agriculture",
  "Industrie",
  "Finance",
  "Commerce",
  "Élevage",
  "E-commerce",
  "Plateforme",
] as const;

export const PHASES_ROADMAP = [
  {
    phase: 1,
    annee: "2026",
    titre: "Lancement",
    description: "9 produits opérationnels, présence Burkina Faso, premières coopératives digitalisées.",
    icon: "🚀",
    milestones: [
      { label: "9 produits en production", done: true },
      { label: "500+ utilisateurs actifs", done: true },
      { label: "Partenariats coopératives BF", done: true },
      { label: "Levée seed round", done: false },
    ],
  },
  {
    phase: 2,
    annee: "2027",
    titre: "Expansion",
    description: "15 produits, déploiement Côte d'Ivoire et Sénégal, 10 000 utilisateurs.",
    icon: "📈",
    milestones: [
      { label: "Expansion Côte d'Ivoire", done: false },
      { label: "Expansion Sénégal", done: false },
      { label: "15 produits actifs", done: false },
      { label: "10 000 utilisateurs", done: false },
    ],
  },
  {
    phase: 3,
    annee: "2028–2029",
    titre: "Consolidation",
    description: "Monopoles sectoriels, intégrations IA, 5 pays, revenu récurrent 1Md FCFA/an.",
    icon: "🏆",
    milestones: [
      { label: "Monopole agriculture BF", done: false },
      { label: "Intégration IA agro", done: false },
      { label: "5 pays couverts", done: false },
      { label: "1 Md FCFA ARR", done: false },
    ],
  },
  {
    phase: 4,
    annee: "2030+",
    titre: "Conglomérat Panafricain",
    description: "Présence dans 15+ pays africains, IPO, infrastructure critique du continent.",
    icon: "🌍",
    milestones: [
      { label: "15+ pays africains", done: false },
      { label: "IPO ou acquisition stratégique", done: false },
      { label: "Infrastructure continentale", done: false },
      { label: "FORGE Afrika = référence tech Afrique", done: false },
    ],
  },
];

export const formatFCFA = (n: number): string =>
  new Intl.NumberFormat("fr-FR").format(n) + " FCFA";
