export const FILIALES_FORGE = [
  {
    nom: "SUGU",
    slug: "sugu",
    categorie: "Retail",
    description: "Gestion de boutique pour les commerçants du secteur informel",
    statut: "Actif" as const,
    couleur: "#F97316",
    icon: "🏪",
    metriques: { utilisateurs: 420, transactions: 3100, ca: 8500000 },
    url: "https://duka.vercel.app",
  },
  {
    nom: "MIFA Life",
    slug: "mifa-life",
    categorie: "E-commerce",
    description: "Marketplace mode africaine et artisanat premium",
    statut: "Actif" as const,
    couleur: "#F59E0B",
    icon: "👗",
    metriques: { utilisateurs: 3400, transactions: 12000, ca: 78000000 },
    url: "https://mifa-life-shop-9k55.vercel.app",
  },
  {
    nom: "TAAMA",
    slug: "taama",
    categorie: "Industrie",
    description: "ERP de traçabilité qualité pour les industries africaines",
    statut: "Actif" as const,
    couleur: "#22C55E",
    icon: "🏭",
    metriques: { utilisateurs: 1240, transactions: 8900, ca: 45000000 },
    url: "https://taama.vercel.app",
  },
  {
    nom: "CompTrack",
    slug: "comptrack",
    categorie: "Finance",
    description: "Comptabilité B2B conforme SYSCOHADA pour les PME africaines",
    statut: "Actif" as const,
    couleur: "#8B5CF6",
    icon: "📊",
    metriques: { utilisateurs: 890, transactions: 45000, ca: 35000000 },
    url: "https://comptrack.vercel.app",
  },
  {
    nom: "FORJA",
    slug: "forja",
    categorie: "Agriculture",
    description: "Gestion des filières agricoles d'export, de la parcelle au conteneur",
    statut: "Actif" as const,
    couleur: "#A16207",
    icon: "☕",
    metriques: { utilisateurs: 560, transactions: 2100, ca: 120000000 },
    url: "https://forja.vercel.app",
  },
  {
    nom: "UEEMT-Tokat",
    slug: "ueemt-tokat",
    categorie: "Communauté",
    description: "Plateforme digitale de l'association des étudiants africains à Tokat",
    statut: "Actif" as const,
    couleur: "#06B6D4",
    icon: "🎓",
    metriques: { utilisateurs: 36, transactions: 0, ca: 0 },
    url: "https://ueemt-tokat.vercel.app",
  },
  {
    nom: "AgroTrack BF",
    slug: "agrotrack-bf",
    categorie: "Agriculture",
    description: "Gestion des collectes et des membres de coopératives au Burkina Faso",
    statut: "Actif" as const,
    couleur: "#10B981",
    icon: "🌾",
    metriques: { utilisateurs: 127, transactions: 1840, ca: 10170000 },
    url: "https://agrotrack-bf.vercel.app",
  },
  {
    nom: "MillTrack",
    slug: "milltrack",
    categorie: "Industrie",
    description: "Gestion de production pour minoteries et huileries",
    statut: "En développement" as const,
    couleur: "#EAB308",
    icon: "⚙️",
    metriques: { utilisateurs: 0, transactions: 0, ca: 0 },
    url: "https://milltrack.vercel.app",
  },
  {
    nom: "LivestockOS",
    slug: "livestockos",
    categorie: "Élevage",
    description: "Gestion des troupeaux, santé animale et marchés de bétail",
    statut: "En développement" as const,
    couleur: "#EF4444",
    icon: "🐄",
    metriques: { utilisateurs: 0, transactions: 0, ca: 0 },
    url: "https://livestock-os.vercel.app",
  },
  {
    nom: "ValueChain Connect",
    slug: "valuechain-connect",
    categorie: "Commerce",
    description: "Marketplace B2B entre producteurs et transformateurs",
    statut: "En développement" as const,
    couleur: "#3B82F6",
    icon: "🔗",
    metriques: { utilisateurs: 0, transactions: 0, ca: 0 },
    url: "https://valuechain-connect.vercel.app",
  },
];

export const CATEGORIES = [
  "Tous",
  "Retail",
  "E-commerce",
  "Industrie",
  "Finance",
  "Agriculture",
  "Communauté",
  "Élevage",
  "Commerce",
] as const;

export const PHASES_ROADMAP = [
  {
    phase: 1,
    annee: "2026",
    titre: "Fondation du Groupe",
    description: "FORGE Afrika s'établit comme entreprise mère : 10 filiales lancées, 6 en production, présence Burkina Faso et diaspora.",
    icon: "🚀",
    milestones: [
      { label: "10 filiales fondées", done: true },
      { label: "6 filiales en production", done: true },
      { label: "Partenariats coopératives BF", done: true },
      { label: "Levée seed round", done: false },
    ],
  },
  {
    phase: 2,
    annee: "2027",
    titre: "Expansion",
    description: "Toutes les filiales en production, déploiement Côte d'Ivoire et Sénégal, 10 000 utilisateurs.",
    icon: "📈",
    milestones: [
      { label: "Expansion Côte d'Ivoire", done: false },
      { label: "Expansion Sénégal", done: false },
      { label: "10 filiales actives", done: false },
      { label: "10 000 utilisateurs", done: false },
    ],
  },
  {
    phase: 3,
    annee: "2028–2029",
    titre: "Consolidation",
    description: "Monopoles sectoriels, intégrations IA, 5 pays, revenu récurrent 1Md FCFA/an.",
    icon: "🏆",
    milestones: [
      { label: "Monopole agriculture BF", done: false },
      { label: "Intégration IA agro", done: false },
      { label: "5 pays couverts", done: false },
      { label: "1 Md FCFA ARR", done: false },
    ],
  },
  {
    phase: 4,
    annee: "2030+",
    titre: "Conglomérat Panafricain",
    description: "Présence dans 15+ pays africains, IPO, infrastructure critique du continent.",
    icon: "🌍",
    milestones: [
      { label: "15+ pays africains", done: false },
      { label: "IPO ou acquisition stratégique", done: false },
      { label: "Infrastructure continentale", done: false },
      { label: "FORGE Afrika = référence tech Afrique", done: false },
    ],
  },
];

export const formatFCFA = (n: number): string =>
  new Intl.NumberFormat("fr-FR").format(n) + " FCFA";
